# Korak 1

# Provjera stanja
GET http://localhost:9200/_cat/health?v

#Korak 2

# Kreiranje indeksa knjige
PUT /knjige
{
  "settings": {
    "analysis": {
      "analyzer": {
        "hrvatski_analyzer": {
          "tokenizer": "standard",
          "filter": ["lowercase", "asciifolding"]
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "naslov": {
        "type": "text",
        "analyzer": "hrvatski_analyzer",
        "fields": {
          "keyword": {
            "type": "keyword"
          }
        }
      },
      "autor": { "type": "keyword" },
      "zanr": { "type": "keyword" },
      "opis": {
        "type": "text",
        "analyzer": "hrvatski_analyzer"
      },
      "godina": { "type": "integer" },
      "cijena": { "type": "double" },
      "dostupno": { "type": "boolean" }
    }
  }
}

# Korak 3

# Unos podataka
POST /knjige/_bulk
{ "index": { "_id": "1" } }
{ "naslov": "Na Drini ćuprija", "autor": "Ivo Andrić", "zanr": "roman", "opis": "Povijesni roman o mostu, ljudima i vremenu.", "godina": 1945, "cijena": 18.50, "dostupno": true }
{ "index": { "_id": "2" } }
{ "naslov": "Derviš i smrt", "autor": "Meša Selimović", "zanr": "roman", "opis": "Filozofski roman o vlasti, pravdi i ljudskoj sudbini.", "godina": 1966, "cijena": 22.00, "dostupno": true }
{ "index": { "_id": "3" } }
{ "naslov": "Tvrđava", "autor": "Meša Selimović", "zanr": "roman", "opis": "Roman o čovjeku, društvu i borbi za smisao.", "godina": 1970, "cijena": 20.00, "dostupno": false }
{ "index": { "_id": "4" } }
{ "naslov": "Travnička hronika", "autor": "Ivo Andrić", "zanr": "povijesni roman", "opis": "Priča o diplomatskom i društvenom životu u Travniku.", "godina": 1942, "cijena": 19.90, "dostupno": true }
{ "index": { "_id": "5" } }
{ "naslov": "Zločin i kazna", "autor": "Fjodor Dostojevski", "zanr": "roman", "opis": "Psihološki roman o krivnji, savjesti i iskupljenju.", "godina": 1866, "cijena": 24.50, "dostupno": true }

# Korak 4

# Pretraga po naslovu
GET /knjige/_search
{
  "query": {
    "match": {
      "naslov": "cuprija"
    }
  }
}

# Pretraga po opisu
GET /knjige/_search
{
  "query": {
    "match": {
      "opis": "pravda vlast sudbina"
    }
  }
}

# Zadatak 3

# Pretraga po pojmu roman
GET /knjige/_search
{
  "query": {
    "match": {
      "opis": "roman"
    }
  }
}

# Korak 5

# Pretraga po autoru
GET /knjige/_search
{
  "query": {
    "term": {
      "autor": "Ivo Andrić"
    }
  }
}

# Bool query
GET /knjige/_search
{
  "query": {
    "bool": {
      "must": [
        { "match": { "opis": "roman" } }
      ],
      "filter": [
        { "term": { "dostupno": true } },
        { "range": { "cijena": { "lte": 22 } } }
      ]
    }
  }
}

# Zadatak 4
GET /knjige/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "opis": "roman"
          }
        }
      ],
      "filter": [
        {"term": {
          "dostupno": "true"
        }},
        {"range": {
          "cijena": {
            "lte": 22
          }
        }}
      ]
    }
  },
  "sort": [
    {
      "cijena": {
        "order": "asc"
      }
    }
  ]
}

# Korak 6

# Analyzer 
POST /knjige/_analyze
{
  "analyzer": "hrvatski_analyzer",
  "text": "Brzi smeđi most preko rijeke!"
}

# Zadatak 5

POST /knjige/_analyze
{
  "analyzer": "hrvatski_analyzer",
  "text": "Na Drini ćuprija"
}

# Zadatak 6

# Agregacija po autoru
GET /knjige/_search
{
  "size": 0,
  "aggs": {
    "knjige_po_autoru": {
      "terms": { "field": "autor" }
    }
  }
}

#Prosjecna cijena po zanru
GET /knjige/_search
{
  "size": 0,
  "aggs": {
    "po_zanru": {
      "terms": { "field": "zanr" },
      "aggs": {
        "prosjecna_cijena": {
          "avg": { "field": "cijena" }
        }
      }
    }
  }
}

# Maks cijena po zanru
GET /knjige/_search
{
  "size": 0,
  "aggs": {
    "dostupne_nedostupne": {
      "terms": { "field": "zanr" },
      "aggs": {
        "dostupne": {
          "max": { "field": "cijena" }
        }
      }
    }
  }
}


# Dostupne i nedostupne
GET /knjige/_search
{
  "size": 0,
  "aggs": {
    "dostupne_nedostupne": {
      "terms": { "field": "dostupno" }
      }
    }
}
